name: Day0 | Create ise01 VM

on:
  workflow_dispatch:

env:
  GOVC_INSECURE: ${{ secrets.VCENTER_INSECURE_CONNECTION }}
  GOVC_URL: ${{ secrets.VCENTER_HOST }}
  GOVC_USERNAME: ${{ secrets.VCENTER_USER }}
  GOVC_PASSWORD: ${{ secrets.VCENTER_PASS }}
  VM_NAME: ise01
  VM_FOLDER: NET
  VM_IP_ADDRESS: ${{ vars.VM_ISE01_IP }}
  VM_IP_CIDR: ${{ vars.VCENTER_DEFAULT_PORT_GROUP_NETMASK }}
  VM_NTP_TIMEZONE: ${{ vars.NTP_TIMEZONE }}
  VM_NTP_SERVER_PRIMARY: ${{ vars.NTP_SERVER_IPV4_PUBLIC_PRIMARY }}
  VM_NTP_SERVER_SECONDARY: ${{ vars.NTP_SERVER_IPV4_PUBLIC_SECONDARY }}
  VM_DATACENTER: ${{ vars.VCENTER_DATACENTER_NAME }}
  VM_DATASTORE: ${{ vars.VCENTER_DATASTORE_NAME }}
  VM_PORT_GROUP: ${{ vars.VCENTER_DEFAULT_PORT_GROUP }}
  CONTENT_LIBRARY: NET
  OVA_IMAGE: Cisco-vISE-300-3.4.0.608.ova
  PATCH_FILE: ise-patchbundle-3.4.0.608-Patch1-24121602.SPA.x86_64.tar.gz

jobs:
  setup-prerequisites:
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    steps:
    - uses: Anush008/clean-after-action@v4.2.0

    - name: Install govc
      run: |
        if ! command -v govc &> /dev/null
        then
            curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" \
                 | sudo tar -C /usr/local/bin -xvzf - govc
        fi
        govc version

    - name: Install expect
      run: |
        if ! command -v expect &> /dev/null
        then
          sudo apt-get update
          sudo apt-get install -y expect
        fi
        expect -v

    - name: Install wget
      run: |
        if ! command -v wget &> /dev/null
        then
          sudo apt-get update
          sudo apt-get install -y wget
        fi

    - name: Install google-chrome
      run: |
        if ! command -v google-chrome &> /dev/null
        then
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
        fi
        google-chrome --version

    - name: Install python3.10-venv
      run: |
        if ! apt list --installed 2>/dev/null | grep -q "python3.10-venv"; then
          sudo apt-get update
          sudo apt-get install -y python3.10-venv
        fi
        python3.10 -m venv --help

  create-ise01-vm:
    needs: setup-prerequisites
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    steps:
    - uses: Anush008/clean-after-action@v4.2.0

    - name: Test vCenter Connectivity
      run: govc about

    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: Rexonix-Connect/cisco-ise-ztp-on-vmware
        path: cisco-ise-ztp-automation-on-vmware

    - name: Convert CIDR to netmask
      run: |
        cidr2mask(){
          OCTETS=$(eval echo '$(((1<<32)-1<<32-$1>>'{3..0}'*8&255))')
          echo "${OCTETS// /.}"
        }
        VM_IP_NETMASK=$(cidr2mask ${{ env.VM_IP_CIDR }})
        echo "VM_IP_NETMASK=${VM_IP_NETMASK}" >> $GITHUB_ENV

    - name: Customize ZTP config
      uses: tvarohohlavy/inplace-envsubst-action@v1.0.0
      env:
        VM_NAME: ${{ env.VM_NAME }}
        VM_IP_ADDRESS: ${{ env.VM_IP_ADDRESS }}
        VM_IP_NETMASK: ${{ env.VM_IP_NETMASK }}
        VM_IP_GATEWAY: ${{ vars.VCENTER_DEFAULT_PORT_GROUP_GATEWAY }}
        VM_DOMAIN_NAME: ${{ vars.VM_DOMAIN_NAME_LAB }}
        VM_DNS_SERVER_PRIMARY: ${{ vars.DNS_SERVER_IPV4_LAB_VIP }}
        VM_NTP_SERVER_PRIMARY: ${{ vars.NTP_SERVER_IPV4_PUBLIC_PRIMARY }}
        VM_NTP_SERVER_SECONDARY: ${{ vars.NTP_SERVER_IPV4_PUBLIC_SECONDARY }}
        VM_NTP_TIMEZONE: ${{ vars.NTP_TIMEZONE }}
        ISE_ADMIN_USERNAME: ${{ secrets.CISCO_ISE_ADMIN_USERNAME }}
        ISE_ADMIN_PASSWORD: ${{ secrets.TEMP_PASSWORD }}
        ISE_SSH_ENABLE: true
        ISE_ERS_ENABLE: true
        ISE_OPENAPI_ENABLE: true
        ISE_PXGRID_ENABLE: true
        ISE_PXGRID_CLOUD_ENABLE: false
        ISE_PATCH_REPO_NAME: TEMP
        ISE_PATCH_REPO_PROTOCOL: http
        ISE_PATCH_REPO_SERVER_NAME: ${{ vars.VM_RUNNER01_IP }}
        ISE_PATCH_REPO_PATH: /
        ISE_PATCH_FILE: ${{ env.PATCH_FILE }}
      with:
        variables: |
          $VM_NAME
          $VM_IP_ADDRESS
          $VM_IP_NETMASK
          $VM_IP_GATEWAY
          $VM_DOMAIN_NAME
          $VM_DNS_SERVER_PRIMARY
          $VM_NTP_SERVER_PRIMARY
          $VM_NTP_SERVER_SECONDARY
          $VM_NTP_TIMEZONE
          $ISE_ADMIN_USERNAME
          $ISE_ADMIN_PASSWORD
          $ISE_SSH_ENABLE
          $ISE_ERS_ENABLE
          $ISE_OPENAPI_ENABLE
          $ISE_PXGRID_ENABLE
          $ISE_PXGRID_CLOUD_ENABLE
          $ISE_PATCH_REPO_NAME
          $ISE_PATCH_REPO_PROTOCOL
          $ISE_PATCH_REPO_SERVER_NAME
          $ISE_PATCH_REPO_PATH
          $ISE_PATCH_FILE
        files: |
          ise01/ise-ztp.conf
        
    - name: Create VM from OVA Template
      id: create-vm
      run: |
        cp cisco-ise-ztp-automation-on-vmware/* .
        cp ise01/ise-ztp.conf .
        chmod +x create-vm.sh
        ./create-vm.sh

    - name: Serve patch file over HTTP and wait until it is downloaded
      run: |
        wget https://github.com/simon-budig/woof/raw/refs/heads/master/woof
        chmod +x woof
        printf "Waiting for the patch file to be downloaded..."
        # NOTE: patch file alredy exists on the runner
        sudo ./woof -p 80 /data/${{ env.PATCH_FILE }}
        printf "Patch file was downloaded."

  initial-ise01-config:
    needs: create-ise01-vm
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    steps:
    - uses: Anush008/clean-after-action@v4.2.0

    - uses: actions/checkout@v4

    - name: Wait for ISE SSH to be ready
      run: |
        printf "Waiting for ISE SSH to be ready..."
        while ! nc -z ${{ env.VM_IP_ADDRESS }} 22; do
          sleep 1
        done
        printf "ISE SSH is ready."

    - name: Reset ISE CLI admin password
      run: |
        expect <<EOF
        set timeout 120
        spawn sshpass -p ${{ secrets.TEMP_PASSWORD }} \
                      ssh -o StrictHostKeyChecking=no \
                          -o UserKnownHostsFile=/dev/null \
                          ${{ secrets.CISCO_ISE_ADMIN_USERNAME }}@${{ env.VM_IP_ADDRESS }}
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "password\r"
        expect "Enter old password:"
        send "${{ secrets.TEMP_PASSWORD }}\r"
        expect "Enter new password:"
        send "${{ secrets.CISCO_ISE_ADMIN_PASSWORD }}\r"
        expect "Confirm new password:"
        send "${{ secrets.CISCO_ISE_ADMIN_PASSWORD }}\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "exit\r"
        expect "closed."
        interact
        EOF

    - name: Wait for ISE to start listening on HTTP(S)
      run: |
        printf "Waiting for ISE HTTP to be ready..."
        while ! nc -z ${{ env.VM_IP_ADDRESS }} 443; do
          sleep 1
        done
        printf "ISE HTTP(S) is ready."

    - name: Wait for ISE Web UI to be ready
      run: |
        URL="https://${{ env.VM_IP_ADDRESS }}:443/admin/login.jsp"
        echo "Waiting for ISE Web UI to return 200 OK..."
        while true; do
          status=$(curl -k -s -o /dev/null -w '%{http_code}' "$URL")
          echo "Check returned status: $status"
          if [ "$status" = "200" ]; then
            echo "Received HTTP 200! Cisco ISE UI appears to be up."
            break
          fi
          sleep 2
        done

    - name: Get ISE information from CLI over SSH
      run: |
        expect <<EOF
        set timeout 120
        spawn sshpass -p ${{ secrets.CISCO_ISE_ADMIN_PASSWORD }} \
                      ssh -o StrictHostKeyChecking=no \
                          -o UserKnownHostsFile=/dev/null \
                          ${{ secrets.CISCO_ISE_ADMIN_USERNAME }}@${{ env.VM_IP_ADDRESS }}
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "screen-length 0\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "screen-width 0\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "show uptime\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "show version\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "show application status ise\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "show logging application ise-psc.log\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "show running-config\r"
        expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
        send "exit\r"
        expect "closed."
        interact
        EOF

    # NOTE: This does not work to avoid another enforced password change when logging in via GUI
    # - name: Reset ISE GUI admin password
    #   run: |
    #     expect <<EOF
    #     set timeout 120
    #     spawn sshpass -p ${{ secrets.CISCO_ISE_ADMIN_PASSWORD }} \
    #                   ssh -o StrictHostKeyChecking=no \
    #                       -o UserKnownHostsFile=/dev/null \
    #                       ${{ secrets.CISCO_ISE_ADMIN_USERNAME }}@${{ env.VM_IP_ADDRESS }}
    #     expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
    #     send "application reset-passwd ise admin\r"
    #     expect {
    #       "Enter new password:" {
    #         # -> ISE is ready; proceed
    #       }
    #       "Application needs to be running in order to reset password" {
    #         # -> Wait a bit, then retry
    #         sleep 10
    #         send "application reset-passwd ise admin\r"
    #         exp_continue
    #       }
    #       timeout {
    #         # -> If we keep timing out, handle error or break
    #         puts "Timeout waiting for application password reset prompt."
    #         exit 1
    #       }
    #     }
    #     send "${{ secrets.CISCO_ISE_ADMIN_PASSWORD }}\r"
    #     expect "Confirm new password:"
    #     send "${{ secrets.CISCO_ISE_ADMIN_PASSWORD }}\r"
    #     expect "${{ env.VM_NAME }}/${{ secrets.CISCO_ISE_ADMIN_USERNAME }}#"
    #     send "exit\r"
    #     expect "closed."
    #     interact
    #     EOF

    - name: Wait for ISE to fully get ready
      run: sleep 600

    - name: Create Python Virtual Environment for Selenium
      run: |
        python3.10 -m venv venv
        source venv/bin/activate
        pip install selenium==4.29.0 \
                    webdriver-manager==4.0.2

    - name: Reset ISE Admin UI password via Selenium
      env:
        ISE_HOST: ${{ env.VM_IP_ADDRESS }}
        ISE_USERNAME: ${{ secrets.CISCO_ISE_ADMIN_USERNAME }}
        ISE_OLD_PASSWORD: ${{ secrets.TEMP_PASSWORD }}
        ISE_NEW_PASSWORD: ${{ secrets.CISCO_ISE_ADMIN_PASSWORD }}
      run: |
        source venv/bin/activate
        python3.10 ise01/selenium-ise-reset-ui-admin-password.py
        
