name: Day0 | Create ise01 VM

on:
  workflow_dispatch:

env:
  VM_NAME: ise01
  VM_FOLDER: NET
  VM_IP_ADDRESS: ${{ vars.VM_ISE01_IP }}
  CONTENT_LIBRARY_NAME: NET
  CONTENT_LIBRARY_ITEM_NAME: Cisco-vISE-300-3.4.0.608
  NTP_TIMEZONE: Europe/Prague
  NTP_SERVER_1: tik.cesnet.cz
  NTP_SERVER_2: tak.cesnet.cz

jobs:
  setup-prerequisites:
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    steps:
    - uses: Anush008/clean-after-action@v4.2.0

    - name: Install govc
      run: |
        if ! command -v govc &> /dev/null
        then
            curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" \
                 | sudo tar -C /usr/local/bin -xvzf - govc
        fi
        govc version

    - name: Test vCenter Connectivity
      env:
        GOVC_INSECURE: ${{ secrets.VCENTER_INSECURE_CONNECTION }}
        GOVC_URL: ${{ secrets.VCENTER_HOST }}
        GOVC_USERNAME: ${{ secrets.VCENTER_USER }}
        GOVC_PASSWORD: ${{ secrets.VCENTER_PASS }}
      run: |
        govc about

  create-ise01-vm:
    needs: setup-prerequisites
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    env:
      GOVC_INSECURE: ${{ secrets.VCENTER_INSECURE_CONNECTION }}
      GOVC_URL: ${{ secrets.VCENTER_HOST }}
      GOVC_USERNAME: ${{ secrets.VCENTER_USER }}
      GOVC_PASSWORD: ${{ secrets.VCENTER_PASS }}
    steps:
    - uses: Anush008/clean-after-action@v4.2.0

    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: rexonix-connect/ise-ztp-automation-on-vmware
        path: ise-ztp-automation-on-vmware
      
    - name: Create VM from OVA Template
      id: create-vm
      run: |
        cp ise-ztp-automation-on-vmware/* .
        chmod +x create-vm.sh
        ./create-vm.sh
